#!/bin/bash
set -euo pipefail
: "${username:=alan}"
: "${password:=demo}"
: "${baseurl:=}"
: "${prefix:=/groupware}"
: "${keycloak:=https://keycloak.opencloud.test}"
: "${realm:=openCloud}"
: "${client_id:=groupware}"
: "${opencloud_container:=opencloud_full-opencloud-1}"
: "${opencloud_local_port:=9200}"

# find out whether we have basic auth enabled
declare -a auth
container=

if exec 6<>/dev/tcp/127.0.0.1/"${opencloud_local_port}"; then
  # running locally
  baseurl="https://localhost:9200"
  # assuming it is with basic auth support
  auth=("-A" "basic" "-a" "${username}:${password}")
elif [[ -n $(docker ps -q -f name="${opencloud_container}") ]]; then
  # container is running
  container=1
  basic_auth=$(docker inspect "${opencloud_container}"|jq -r '.[].Config.Env[]|select(match("^PROXY_ENABLE_BASIC_AUTH="))|.[index("=")+1:]')
  if [[ "${basic_auth}" == "true" ]]; then
    auth=("-A" "basic" "-a" "${username}:${password}")
  else
    # empty auth array, will trigger fetching an access token
    auth=()
  fi
else
  # not listening locally, nor running as a container
  if [[ -z "${baseurl}" ]]; then
    echo "ERROR: not running locally on \${opencloud_local_port} (${opencloud_local_port}) nor running as a container \${opencloud_container} ('${opencloud_container}') and \${baseurl} is not set either" >&2
    exit 9
  else
    # assuming we need to fetch a token
    auth=()
  fi
fi

exec 6>&- # close output connection
exec 6<&- # close input connection

url="${baseurl}"
if [[ -z "${url}" ]]; then
  if [[ -n "${container}" ]]; then
    url="https://cloud.opencloud.test"
  else
    url="https://localhost:9200"
  fi
fi

declare -a args
for a in "$@"; do
  case "$a" in
    //*) args+=("${url}${prefix}${a#/}");;
    /*) args+=("${url}$a");;
    *) args+=("$a");;
  esac
done

if [[ ${#auth[@]} == 0 ]]; then
  token=$(curl --silent --insecure --fail -X POST "${keycloak}/realms/${realm}/protocol/openid-connect/token" -d username="${username}" -d password="${password}" -d grant_type=password -d client_id="${client_id}" -d scope=openid | jq -r '.access_token')
  auth=("-A" "bearer" "-a" "$token")
fi

traceId=$(echo $RANDOM | md5sum | head -c 16)

[[ -n "${HTTP-}" ]] && exec $HTTP --verify=no ${auth[@]} "${args[@]}" "Trace-Id:${traceId}"
type -p https &>/dev/null && exec https --verify=no ${auth[@]} "${args[@]}" "Trace-Id:${traceId}"
type -p xh &>/dev/null && exec xh --verify=no ${auth[@]} "${args[@]}" "Trace-Id:${traceId}"

echo "ERROR: must install httpie or xh" >&2
