#!/bin/bash
set -euo pipefail
: "${username:=alan}"
: "${password:=demo}"
: "${stalwart:=https://stalwart.opencloud.test}"

declare -a args
url=''
for a in "$@"; do
  case "$a" in
    /*) args+=("${stalwart}$a");;
    *) args+=("$a");;
  esac
done

exec xh --verify=no -I --pretty=all --follow --max-redirects=2 -a "${username}:${password}" "${args[@]}"
